export const TEAM_COLORS: Record<string, string> = {
  // Grupo A
  México: '#006847',
  'África do Sul': '#007A4D',
  'Coreia do Sul': '#003478',
  'Rep. Tcheca': '#D7141A',

  // Grupo B
  Canadá: '#FF0000',
  Catar: '#8D1B3D',
  Suíça: '#FF0000',
  'Bósnia e Herzegovina': '#002395',

  // Grupo C
  Brasil: '#009C3B',
  Marrocos: '#C1272D',
  Haiti: '#003F87',
  Escócia: '#003F87',

  // Grupo D
  'Estados Unidos': '#B22234',
  Paraguai: '#D52B1E',
  Austrália: '#00008B',
  Turquia: '#E30A17',

  // Grupo E
  Alemanha: '#1a1a2e',
  Curaçao: '#002395',
  'Costa do Marfim': '#F77F00',
  Equador: '#FFD100',

  // Grupo F
  Holanda: '#FF6200',
  Japão: '#BC002D',
  Suécia: '#006AA7',
  Tunísia: '#E70013',

  // Grupo G
  Espanha: '#AA151B',
  'Cabo Verde': '#003893',
  'Arábia Saudita': '#006C35',
  Uruguai: '#75AADB',

  // Grupo H
  Bélgica: '#EF3340',
  Egito: '#CC1F18',
  Irã: '#239F40',
  'Nova Zelândia': '#00247D',

  // Grupo I
  França: '#003189',
  Senegal: '#00853F',
  Noruega: '#EF2B2D',
  Iraque: '#CE1126',

  // Grupo J
  Argentina: '#74ACDF',
  Argélia: '#006233',
  Áustria: '#ED2939',
  Jordânia: '#007A3D',

  // Grupo K
  Inglaterra: '#012169',
  Croácia: '#FF0000',
  Gana: '#006B3F',
  Panamá: '#DA121A',

  // Grupo L
  Portugal: '#CC0000',
  Uzbequistão: '#1EB53A',
  Colômbia: '#FCD116',
  'Rep. Dem. do Congo': '#007FFF',
}

export const TEAM_STARS: Record<string, { name: string; position: string }> = {
  // Top globais primeiro — aparecem no banner (baseado nas listas oficiais Copa 2026)
  Brasil: { name: 'Neymar', position: 'ATK' },
  Argentina: { name: 'L. Messi', position: 'ATK' },
  França: { name: 'K. Mbappé', position: 'ATK' },
  Portugal: { name: 'C. Ronaldo', position: 'ATK' },
  Noruega: { name: 'E. Haaland', position: 'ATK' },
  Inglaterra: { name: 'H. Kane', position: 'ATK' },
  Egito: { name: 'M. Salah', position: 'ATK' },
  Senegal: { name: 'Sadio Mane', position: 'ATK' },
  Espanha: { name: 'Lamine Yamal', position: 'ATK' },
  Alemanha: { name: 'F. Wirtz', position: 'MID' },
  Bélgica: { name: 'K. De Bruyne', position: 'MID' },
  Croácia: { name: 'L. Modrić', position: 'MID' },
  Colômbia: { name: 'James Rodriguez', position: 'MID' },
  Marrocos: { name: 'A. Hakimi', position: 'DEF' },
  'Coreia do Sul': { name: 'Son Heung-min', position: 'ATK' },
  'Estados Unidos': { name: 'C. Pulisic', position: 'ATK' },
  Holanda: { name: 'C. Gakpo', position: 'ATK' },
  Uruguai: { name: 'F. Valverde', position: 'MID' },
  Japão: { name: 'T. Kubo', position: 'MID' },
  Canadá: { name: 'A. Davies', position: 'DEF' },
  México: { name: 'S. Giménez', position: 'ATK' },
  Equador: { name: 'M. Caicedo', position: 'MID' },
  Turquia: { name: 'Arda Guler', position: 'MID' },
  Suécia: { name: 'V. Gyökeres', position: 'ATK' },
  Suíça: { name: 'G. Xhaka', position: 'MID' },
  Argélia: { name: 'R. Mahrez', position: 'ATK' },
  Gana: { name: 'T. Partey', position: 'MID' },
  Paraguai: { name: 'M. Almirón', position: 'ATK' },
  'Arábia Saudita': { name: 'S. Al-Dawsari', position: 'ATK' },
  Áustria: { name: 'D. Alaba', position: 'DEF' },
  'Rep. Tcheca': { name: 'P. Schick', position: 'ATK' },
  'Costa do Marfim': { name: 'Amad Diallo', position: 'ATK' },
  Irã: { name: 'M. Taremi', position: 'ATK' },
  Austrália: { name: 'M. Leckie', position: 'ATK' },
  Escócia: { name: 'S. McTominay', position: 'MID' },
  Tunísia: { name: 'H. Mejbri', position: 'MID' },
  'Bósnia e Herzegovina': { name: 'E. Džeko', position: 'ATK' },
  Catar: { name: 'A. Afif', position: 'ATK' },
  'África do Sul': { name: 'R. Mofokeng', position: 'ATK' },
  'Cabo Verde': { name: 'Jovane Cabral', position: 'ATK' },
  Uzbequistão: { name: 'E. Shomurodov', position: 'ATK' },
  'Rep. Dem. do Congo': { name: 'Y. Wissa', position: 'ATK' },
  Haiti: { name: 'W. Isidor', position: 'ATK' },
  Curaçao: { name: 'T. Chong', position: 'MID' },
  'Nova Zelândia': { name: 'C. Wood', position: 'ATK' },
  Iraque: { name: 'A. Al-Hamadi', position: 'ATK' },
  Jordânia: { name: 'M. Al-Taamari', position: 'ATK' },
  Panamá: { name: 'A. Godoy', position: 'MID' },
}

/** Maps team name → emoji flag character for use without a Match record */
export const TEAM_FLAGS: Record<string, string> = {
  México: '🇲🇽',
  'África do Sul': '🇿🇦',
  'Coreia do Sul': '🇰🇷',
  'Rep. Tcheca': '🇨🇿',
  Canadá: '🇨🇦',
  Catar: '🇶🇦',
  Suíça: '🇨🇭',
  'Bósnia e Herzegovina': '🇧🇦',
  Brasil: '🇧🇷',
  Marrocos: '🇲🇦',
  Haiti: '🇭🇹',
  Escócia: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Estados Unidos': '🇺🇸',
  Paraguai: '🇵🇾',
  Austrália: '🇦🇺',
  Turquia: '🇹🇷',
  Alemanha: '🇩🇪',
  Curaçao: '🇨🇼',
  'Costa do Marfim': '🇨🇮',
  Equador: '🇪🇨',
  Holanda: '🇳🇱',
  Japão: '🇯🇵',
  Suécia: '🇸🇪',
  Tunísia: '🇹🇳',
  Espanha: '🇪🇸',
  'Cabo Verde': '🇨🇻',
  'Arábia Saudita': '🇸🇦',
  Uruguai: '🇺🇾',
  Bélgica: '🇧🇪',
  Egito: '🇪🇬',
  Irã: '🇮🇷',
  'Nova Zelândia': '🇳🇿',
  França: '🇫🇷',
  Senegal: '🇸🇳',
  Noruega: '🇳🇴',
  Iraque: '🇮🇶',
  Argentina: '🇦🇷',
  Argélia: '🇩🇿',
  Áustria: '🇦🇹',
  Jordânia: '🇯🇴',
  Inglaterra: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Croácia: '🇭🇷',
  Gana: '🇬🇭',
  Panamá: '🇵🇦',
  Portugal: '🇵🇹',
  Uzbequistão: '🇺🇿',
  Colômbia: '🇨🇴',
  'Rep. Dem. do Congo': '🇨🇩',
}

/** Main goalkeeper per national team for award candidate lists */
export const TEAM_GOALKEEPERS: Record<string, { name: string; position: 'GK' }> = {
  Brasil: { name: 'Ederson', position: 'GK' },
  Argentina: { name: 'E. Martínez', position: 'GK' },
  França: { name: 'M. Maignan', position: 'GK' },
  Portugal: { name: 'D. Costa', position: 'GK' },
  Espanha: { name: 'U. Simón', position: 'GK' },
  Alemanha: { name: 'M. ter Stegen', position: 'GK' },
  Inglaterra: { name: 'J. Pickford', position: 'GK' },
  Bélgica: { name: 'K. Casteels', position: 'GK' },
  Holanda: { name: 'B. Flekken', position: 'GK' },
  Croácia: { name: 'D. Livaković', position: 'GK' },
  Senegal: { name: 'E. Mendy', position: 'GK' },
  Marrocos: { name: 'Y. Bounou', position: 'GK' },
  Uruguai: { name: 'S. Rochet', position: 'GK' },
  Colômbia: { name: 'C. Vargas', position: 'GK' },
  México: { name: 'G. Ochoa', position: 'GK' },
  'Estados Unidos': { name: 'M. Turner', position: 'GK' },
  Japão: { name: 'S. Gonda', position: 'GK' },
  'Coreia do Sul': { name: 'K. Seung-gyu', position: 'GK' },
  Austrália: { name: 'M. Ryan', position: 'GK' },
  Suíça: { name: 'Y. Sommer', position: 'GK' },
  Noruega: { name: 'R. Nyland', position: 'GK' },
  Suécia: { name: 'R. Olsen', position: 'GK' },
  Turquia: { name: 'A. Günok', position: 'GK' },
  Irã: { name: 'A. Beiranvand', position: 'GK' },
  Egito: { name: 'M. El-Shenawy', position: 'GK' },
  Canadá: { name: 'M. Crepeau', position: 'GK' },
  Equador: { name: 'H. Galíndez', position: 'GK' },
  Paraguai: { name: 'A. Silva', position: 'GK' },
  'Arábia Saudita': { name: 'M. Al-Owais', position: 'GK' },
  Catar: { name: 'S. Al-Sheeb', position: 'GK' },
  Argélia: { name: 'R. Mandrea', position: 'GK' },
  Tunísia: { name: 'A. Dahmen', position: 'GK' },
  Gana: { name: 'L. Ati Zigi', position: 'GK' },
  'Costa do Marfim': { name: 'Y. Fofana', position: 'GK' },
  Escócia: { name: 'A. Gunn', position: 'GK' },
  'Bósnia e Herzegovina': { name: 'I. Pirić', position: 'GK' },
  Iraque: { name: 'J. Kassid', position: 'GK' },
  Jordânia: { name: 'Y. Shambari', position: 'GK' },
  Haiti: { name: 'O. Janvier', position: 'GK' },
  Panamá: { name: 'L. Mejía', position: 'GK' },
  'Nova Zelândia': { name: 'O. Sail', position: 'GK' },
  Uzbequistão: { name: 'I. Nematov', position: 'GK' },
  'Rep. Dem. do Congo': { name: 'G. Mpasi', position: 'GK' },
  'Cabo Verde': { name: 'V. Mendes', position: 'GK' },
  'África do Sul': { name: 'R. Williams', position: 'GK' },
  Curaçao: { name: 'E. Marcellis', position: 'GK' },
  Áustria: { name: 'P. Pentz', position: 'GK' },
  'Rep. Tcheca': { name: 'J. Staněk', position: 'GK' },
}
