export const TEAM_COLORS: Record<string, string> = {
  Brazil: '#009C3B',
  Argentina: '#74ACDF',
  France: '#003189',
  Portugal: '#CC0000',
  Germany: '#1a1a2e',
  Spain: '#AA151B',
  England: '#012169',
  Netherlands: '#FF6200',
  Belgium: '#EF3340',
  Uruguay: '#75AADB',
  Colombia: '#FCD116',
  Mexico: '#006847',
  'United States': '#B22234',
  Canada: '#FF0000',
  Japan: '#BC002D',
  'South Korea': '#003478',
  Morocco: '#C1272D',
  Senegal: '#00853F',
  Nigeria: '#008751',
  Ghana: '#006B3F',
  Ecuador: '#FFD100',
  Switzerland: '#FF0000',
  Poland: '#DC143C',
  Croatia: '#FF0000',
  Serbia: '#C6363C',
  Denmark: '#C60C30',
  Austria: '#ED2939',
  Turkey: '#E30A17',
  Iran: '#239F40',
  Australia: '#00008B',
  Norway: '#EF2B2D',
  Ukraine: '#005BBB',
  Italy: '#003399',
}

export const TEAM_STARS: Record<string, { name: string; position: string }> = {
  Brazil: { name: 'Vinicius Jr.', position: 'ATK' },
  Argentina: { name: 'L. Messi', position: 'ATK' },
  France: { name: 'K. Mbappé', position: 'ATK' },
  Portugal: { name: 'C. Ronaldo', position: 'ATK' },
  Germany: { name: 'J. Musiala', position: 'MID' },
  Spain: { name: 'Pedri', position: 'MID' },
  England: { name: 'J. Bellingham', position: 'MID' },
  Netherlands: { name: 'V. van Dijk', position: 'DEF' },
  Belgium: { name: 'K. De Bruyne', position: 'MID' },
  Uruguay: { name: 'D. Núñez', position: 'ATK' },
  Colombia: { name: 'L. Díaz', position: 'ATK' },
  Mexico: { name: 'H. Lozano', position: 'ATK' },
  'United States': { name: 'C. Pulisic', position: 'ATK' },
  Canada: { name: 'A. Davies', position: 'DEF' },
  Japan: { name: 'T. Kubo', position: 'MID' },
  'South Korea': { name: 'Son H.', position: 'ATK' },
  Morocco: { name: 'A. Hakimi', position: 'DEF' },
  Senegal: { name: 'S. Mané', position: 'ATK' },
  Nigeria: { name: 'V. Osimhen', position: 'ATK' },
  Norway: { name: 'E. Haaland', position: 'ATK' },
  Ecuador: { name: 'E. Caicedo', position: 'MID' },
  Croatia: { name: 'L. Modrić', position: 'MID' },
  Switzerland: { name: 'G. Xhaka', position: 'MID' },
  Denmark: { name: 'C. Eriksen', position: 'MID' },
  Poland: { name: 'R. Lewandowski', position: 'ATK' },
  Serbia: { name: 'D. Vlahović', position: 'ATK' },
  Austria: { name: 'M. Sabitzer', position: 'MID' },
  Turkey: { name: 'H. Çalhanoğlu', position: 'MID' },
  Iran: { name: 'M. Taremi', position: 'ATK' },
  Australia: { name: 'M. Leckie', position: 'ATK' },
  Ukraine: { name: 'M. Mudryk', position: 'ATK' },
  Italy: { name: 'G. Donnarumma', position: 'GK' },
}
